### ISSUE TITLE
Makefile to work on ARCH, 1 line change

### ISSUE THREAD

**Issue by sp2004c** [ccstolley/ircl#3]
does not build on Arch / Manjaro until the Makefile reads sth. like:
`
CFLAGS = -fstack-protector-all -fbounds-check -std=gnu11 -pedantic -Wall -Wextra ${INCS}   ${CPPFLAGS}       -g
`

so   **-std=gnu11**   is helpful here

`//#include <sys/select.h>`
in .h won't hurt   in -std=c99

**Comment by ccstolley** [comment]
I think you'll need more than that to get a linux build to work. I took a stab at it here: https://github.com/ccstolley/ircl/tree/linux_build  but needs a bit more build system work before I can merge it in.

**Comment by ccstolley** [comment]
I merged it in and incorporated your suggestion as well. Thanks!
